using TestProject.Common.DTO.ExecutionResult;
using TestProject.Common.Enums;
using System;
using System.Reflection;
using TestProject.SDK;

namespace TestProject.Generated.Tests.MyFirstProject
{
	/// <summary>
	/// This class was automatically generated by TestProject
	/// Provides an example how to run coded TestProject tests
	/// </summary>
	public class MyFirstProjectRunner
	{
		public static string DevToken = "C2rua6A0Q7gcKtbtTkFcWg6RtiHN0Ska0WVhy4G4hjY";
		public static AutomatedBrowserType Browser = AutomatedBrowserType.Chrome;
		public static StepExecutionResult RunWebtest()
		{
			using (var runner = new RunnerBuilder(DevToken).AsWeb(Browser).Build())
				return runner.Run(new Webtest(), true);
		}

		public static void Main(string[] args)
		{
			try
			{
				RunWebtest();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex);
			}
		}
	}
}